

spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8

# 自定义系统配置
kata:
  regexp:
    mobile: ^(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$
    telephone: ^(\(\d{3,4}-)|\d{3.4}-)?\d{7,8}$