server:
  port: 8080

spring:
  profiles:
    active: dev
  # 国际化消息
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
  # 配置json日期格式与时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    scheduling:
      # 设置定时任务线程数
      pool:
        size: 5
  servlet:
    # 开启文件上传
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB


# 自定义应用配置
kata:
  regexp:
    mobile: ^(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$
    telephone: ^(\(\d{3,4}-)|\d{3.4}-)?\d{7,8}$


# 控制面板
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
